[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cấu hình chuyển hướng và rewrite
[[redirects]]
  from = "/api/*"
  to = "http://103.163.118.194:8080/:splat"
  status = 200
  force = true

